config/routes.rb
# frozen_string_literal: true

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :example, only: [:index]

post 'github_webhook', to: 'webhooks#github_webhook_catcher'
post 'semaphore_webhook', to: 'webhooks#semaphore_webhook_catcher'
get 'sync_pull_requests', to: 'sync#sync_pull_requests'

app/models/deployment.rb
# frozen_string_literal: true

class Deployment < GnosisApplicationRecord
  belongs_to :pull_request
  has_one :issue, through: :pull_request, source: :issue

  def self.auto_create_or_update(branch, pull_request_id, url, has_passed, ci_date_string)
    ci_date = Time.zone.parse(ci_date_string)
    deploy = Deployment.find_or_initialize_by(deploy_branch: branch, pull_request_id: pull_request_id)
    deploy.update!(url: url, has_passed: has_passed, ci_date: ci_date)
  end
end

app/models/gnosis_application_record.rb
# frozen_string_literal: true

# rubocop:disable Rails/ApplicationRecord
class GnosisApplicationRecord < ActiveRecord::Base
  # rubocop:enable Rails/ApplicationRecord
  self.abstract_class = true
end

app/models/number_extractor.rb
# frozen_string_literal: true

class NumberExtractor
  DIG_FIND_DATA = [
    { keys: %i[pull_request head ref], match_regex: %r{/(\d+)} },
    { keys: %i[pull_request body], match_regex: /TICKET-(\d+)/ },
  ].freeze

  def self.call(params)
    DIG_FIND_DATA.lazy.map do |data|
      match = params.dig(*data[:keys])&.match(data[:match_regex])
      match[1] if match
      # rubocop:disable Style/CollectionCompact
    end.reject(&:nil?).first
    # rubocop:enable Style/CollectionCompact
  end
end

app/models/pull_request.rb
# frozen_string_literal: true

class PullRequest < GnosisApplicationRecord
  belongs_to :issue
  has_many :pull_request_deployments, dependent: :destroy

  def self.auto_create_or_update(webhook_params)
    state = webhook_params[:pull_request][:merged] ? 'merged' : webhook_params[:pull_request][:state]
    state = 'draft' if state == 'open' && webhook_params[:pull_request][:draft]

    return if Issue.find_by(id: webhook_params[:issue_id]).nil?

    pr = PullRequest.find_or_initialize_by(url: webhook_params[:pull_request][:html_url])
    pr.update!(state: state,
               url: webhook_params[:pull_request][:html_url],
               title: webhook_params[:pull_request][:title],
               source_branch: webhook_params[:pull_request][:head][:ref],
               target_branch: webhook_params[:pull_request][:base][:ref],
               was_merged: webhook_params[:pull_request][:merged],
               merge_commit_sha: webhook_params[:pull_request][:merge_commit_sha],
               issue_id: webhook_params[:issue_id])
  end
end

app/models/pull_request_deployment.rb
# frozen_string_literal: true

class PullRequestDeployment < GnosisApplicationRecord
  belongs_to :pull_request
  has_one :issue, through: :pull_request, source: :issue

  def self.auto_create_or_update(branch, pull_request_id, url, has_passed, ci_date_string)
    ci_date = Time.zone.parse(ci_date_string)
    deploy = PullRequestDeployment.find_or_initialize_by(deploy_branch: branch, pull_request_id: pull_request_id)
    deploy.update!(url: url, has_passed: has_passed, ci_date: ci_date)
  end
end

app/controllers/sync_controller.rb
# frozen_string_literal: true

class SyncController < ApplicationController
  before_action :require_admin

  def sync_pull_requests
    SyncJob.perform_now
    render plain: 'Pull request syncing started. This may take a while.'
  rescue StandardError => e
    Rails.logger.error(e)
    render plain: 'There was an error while syncing the pull requests, please check the logs.',
           status: :internal_server_error
  end
end

app/controllers/webhooks_controller.rb
# frozen_string_literal: true

class WebhooksController < ApplicationController
  protect_from_forgery except: %i[github_webhook_catcher semaphore_webhook_catcher]

  def github_webhook_catcher
    unless verify_signature(request.body.read, request.env['HTTP_X_HUB_SIGNATURE_256'],
                            ENV.fetch('GITHUB_WEBHOOK_SECRET'))
      return render json: {status: 403}, status: :forbidden
    end

    WebhookHandler.new.handle_github(params)

    render json: {status: :ok}
  end

  def semaphore_webhook_catcher
    unless verify_signature(request.body.read, "sha256=#{request.headers['X-Semaphore-Signature-256']}",
                            ENV.fetch('SEMAPHORE_WEBHOOK_SECRET'))
      return render json: {status: 403}, status: :forbidden
    end

    WebhookHandler.new.handle_semaphore(params)

    render json: {status: :ok}
  end

  def check_if_login_required
    false # No login required as this uses the "verify_signature" for validation
  end

  private

  def verify_signature(payload_body, recieved_signature, secret)
    signature = "sha256=#{OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), secret, payload_body)}"
    Rack::Utils.secure_compare(signature, recieved_signature)
  end
end

app/views/settings/_gnosis_settings.erb
<table>
  <tbody>
  <tr>
    <th>Sync pull requests for</th>
    <td>
      <input type="text" id="settings_notification_default"
             value="<%= ENV.fetch('GITHUB_ORGANIZATION_NAME') %>"
             disabled
             name="settings[github_access_token]" >
      <label>
      </label>
      <button id="sync-button" data-url="<%= sync_pull_requests_path %>">Sync</button>
      <span>(takes a very long time!)</span>

      <script>
          document.querySelector('#sync-button').addEventListener('click', function () {
              this.disabled = true;
              this.innerText = 'Syncing...';

              const handleError = (error) => {
                  this.innerText = 'Sync failed!';
                  console.error(error);
              }

              const handleResponse = (response) => {
                  if (response.ok) {
                      this.innerText = 'Synced!';
                  } else {
                      handleError()
                  }
              }

              fetch(this.dataset.url, {method: 'GET'})
                .then(handleResponse)
                .catch(handleError)
          })
      </script>
    </td>
  </tr>
  </tbody>
</table>